services:
  frontend:
    build:
      context: ./frontend-bpm
      dockerfile: Dockerfile.dev
    image: frontend-bpm-image-dev
    container_name: frontend-bpm-dev
    develop:
      watch:
        - action: sync
          path: ./frontend-bpm/src
          target: /app/src
#    networks:
#      - app_network

  # backend-bpm:
  #   build: ./backend-bpm/compose.yaml
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app_network

#networks:
#  app_network:
#    driver: bridge

# Shared volumes if needed
# volumes:
#   shared_data: