services:
  frontend:
    image: frontend-bpm-image-dev
    container_name: frontend-bpm-dev
    build:
      context: ./frontend-bpm
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: sync
          path: ./frontend-bpm/src
          target: /app/src

  backend:
    image: backend-bpm-image-dev
    container_name: backend-bpm-dev
    build:
      context: ./backend-bpm
      dockerfile: Dockerfile
    ports:
      - 8000:4000


  db:
    image: postgres:12
    container_name: db-bpm-dev
    ports:
      - "5432:5432"