services:
  frontend:
    image: frontend-bpm-image-dev
    container_name: frontend-bpm-dev
    build:
      context: ./frontend-bpm
      dockerfile: Dockerfile.dev
    # Il Bind Mount è necessario per lo sviluppo Angular:
    # 1. Rende il codice sorgente locale immediatamente disponibile nel container (/app è il WORKDIR).
    # 2. Risolve i problemi di hot reload (Live Reload / HMR) con Webpack/Angular CLI su macOS/Windows,
    #    dove il file watcher nativo del container non riceve le notifiche di cambio file dall'host.
    volumes:
      - ./frontend-bpm:/app

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "15432:80"    # Keep port :80 inside container as per pgadmin official documentation
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgadmin-data: {}
