"""parking_event

Revision ID: 3b4ccf127a4a
Revises: f7375e8cef78
Create Date: 2025-12-04 18:39:49.949601

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '3b4ccf127a4a'
down_revision = 'f7375e8cef78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('parking_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('PARK', 'LEAVE', name='eventtype'), nullable=False),
    sa.Column('location_point', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parking_area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parking_area_id'], ['parking_areas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_parking_events_location_point', 'parking_events', ['location_point'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_parking_events_location_point', table_name='parking_events', postgresql_using='gist', column_name='location_point')
    op.drop_geospatial_table('parking_events')
    # ### end Alembic commands ###
