"""parking_event_nullable_area_id

Revision ID: 471d4774bd0d
Revises: 4a081d29fe28
Create Date: 2026-01-17 13:47:07.025139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471d4774bd0d'
down_revision = '4a081d29fe28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parking_events', 'parking_area_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parking_events', 'parking_area_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
