"""parking_event_start_end_time

Revision ID: 4a081d29fe28
Revises: 3b4ccf127a4a
Create Date: 2025-12-10 17:32:17.109063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a081d29fe28'
down_revision = '3b4ccf127a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_events', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('parking_events', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.drop_column('parking_events', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_events', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('parking_events', 'end_time')
    op.drop_column('parking_events', 'start_time')
    # ### end Alembic commands ###
