"""Added mail to user

Revision ID: 587f37b5bded
Revises: 4a081d29fe28
Create Date: 2026-01-12 12:00:25.804029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587f37b5bded'
down_revision = '4a081d29fe28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
