"""parking_areas

Revision ID: f7375e8cef78
Revises: 67e307c0de15
Create Date: 2025-12-04 18:22:49.266136

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = 'f7375e8cef78'
down_revision = '67e307c0de15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('parking_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_area', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('residual_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_geospatial_index('idx_parking_areas_location_area', 'parking_areas', ['location_area'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_parking_areas_location_area', table_name='parking_areas', postgresql_using='gist', column_name='location_area')
    op.drop_geospatial_table('parking_areas')
    # ### end Alembic commands ###
